modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "LGPL-2.1"

[[mods]]
modId = "figura"
version = "${version}"
displayName = "Figura"
authors = "Zandra & Blancworks"
description = '''
Figura is a client-side mod that allows players to change their player model and highly customize it, while also letting other players see their models safely.
'''
#logoFile = ""

[[dependencies.figura]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.figura]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.figura]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"